---
  default_gene: PF3D7_0304600
  ch10x:
    cell:
      columns: [ stage, day ]
      data: []
      genes: []
      pca: 3
      popup: 'Stage: [[0]]<br />Day: [[1]]'
      umap: 3
  ss2:
    cell:
      columns: [ stage, host ]
      data: []
      genes: []
      popup: 'Stage: [[0]]<br />Host: [[1]]'
      umap: 2
    gene:
      data: []
      knn: 2
      popup: 'Gene ID: [[1]]<br />Gene name: [[5]]<br />Cluster: [[0]]'
      table: |-2

                  <h3>[[1]]</h3>
                  <dl>
                    <dt>Transcript ID</dt> <dd>[[2]]</dd>
                    <dt>Product description</dt> <dd>[[3]]</dd>
                    <dt>Gene type</dt> <dd>[[4]]</dd>
                    <dt>Gene name</dt> <dd>[[5]]</dd>
                    <dt>Cluster</dt> <dd>[[0]]</dd>
                    <dt>Conservation score with <i>P.Berghei</i></dt> <dd>[[6]]</dd>
                    <dt>Conserved female marker</dt> <dd>[[7]]</dd>
                    <dt>Conserved male marker</dt> <dd>[[8]]</dd>
                    <dt>Conserved ookinete marker</dt> <dd>[[9]]</dd>
                    <dt>Conserved sporozoite marker</dt> <dd>[[10]]</dd>
                  </dl>

